Adding cache and cache manager implementation
ehcache/ehcache-shiro pull request #1
Opened 2016-09-26 14:17 UTC by nenko-tabakov

Added implementation for Shiro's Cache and CacheManager.
Added pom.xml

2016-09-26 14:19 UTC, ljacomet commented
test this please

2016-09-26 14:19 UTC, terracotta-org commented
Can one of the admins verify this patch?

2016-09-26 14:38 UTC, ljacomet commented on pom.xml
> +        </dependency>
Needs to be declared as `provided`

2016-09-26 14:38 UTC, ljacomet commented on pom.xml
> +        </dependency>
needs to be declared as `provided`

2016-09-26 14:39 UTC, ljacomet commented on src/main/java/org/ehcache/integrations/shiro/EhCache.java
> +    private static final Logger log = LoggerFactory.getLogger(EhCache.class);
The Ehcache code style is 2 spaces. Can we use that here as well?

2016-09-26 14:40 UTC, ljacomet commented on src/main/java/org/ehcache/integrations/shiro/EhCache.java
> +public class EhCache<K, V> implements Cache<K, V> {
I would name that `ShiroEhcache` or `EhcacheShiro` for example. `EhCache` feels weird in this context

2016-09-26 14:41 UTC, ljacomet commented on src/main/java/org/ehcache/integrations/shiro/EhCache.java
> +        log.trace(operation + " using cache [" + cache + "] for key [" + k + "]");
We should use slf4j property substitution.

2016-09-26 14:42 UTC, ljacomet requested changes
Remarks on build and code style mostly

2016-09-26 22:09 UTC, chrisdennis commented on src/main/java/org/ehcache/integrations/shiro/EhCache.java
> +        log.trace(operation + " using cache [" + cache + "] for key [" + k + "]");
If we do that in other places we can probably get rid of the guarding if statements on the logging calls too right?

2016-09-26 22:10 UTC, chrisdennis commented on src/main/java/org/ehcache/integrations/shiro/EhCache.java
> +        cache.put(k, v);
This should probably be `cache.getAndPut(k, v);` otherwise it's not atomic (which it probably wants to be).

2016-09-26 22:11 UTC, chrisdennis commented on src/main/java/org/ehcache/integrations/shiro/EhCache.java
> +        cache.remove(k);
This should probably be `cache.getAndRemove(k);` to make sure it's atomic too.

2016-09-26 22:14 UTC, chrisdennis commented on src/main/java/org/ehcache/integrations/shiro/EhCache.java
> +    public Set<K> keys() {
It seems like this might benefit from using a wrapper class over the cache rather than duplicating the cache key-set in heap.

2016-09-26 22:15 UTC, chrisdennis commented on src/main/java/org/ehcache/integrations/shiro/EhCache.java
> +    public Collection<V> values() {
Same as on keys, a wrapper type is likely a good choice here.

2016-09-26 22:17 UTC, chrisdennis commented on src/main/java/org/ehcache/integrations/shiro/EhCacheManager.java
> +            CacheConfigurationBuilder<Object, Object> configurationBuilder = xmlConfiguration.newCacheConfigurationBuilderFromTemplate(
Is this contract of using a cache template definition named "defaultCacheConfiguration" a behavior defined by Shiro or is it something we added?

2016-09-26 22:18 UTC, chrisdennis commented on src/main/java/org/ehcache/integrations/shiro/EhCacheManager.java
> +            manager = CacheManagerBuilder.newCacheManager(createConfiguration());
Why is it that we have to do this lazily?  Seems like this class could be a lot simpler if we just created the cache manager at construction time.

2016-09-27 07:17 UTC, nenko-tabakov commented on src/main/java/org/ehcache/integrations/shiro/EhCache.java
> +        cache.put(k, v);
Isn't `cache.getAndPut(k, v);` JCache API?

2016-09-27 07:17 UTC, nenko-tabakov commented on src/main/java/org/ehcache/integrations/shiro/EhCache.java
> +        cache.remove(k);
Isn't `cache.getAndRemove(k)` JCache API?

2016-09-27 11:59 UTC, nenko-tabakov commented on src/main/java/org/ehcache/integrations/shiro/EhCacheManager.java
> +            CacheConfigurationBuilder<Object, Object> configurationBuilder = xmlConfiguration.newCacheConfigurationBuilderFromTemplate(
There is a default cache configuration in the Shiro's CacheManager using EhCache 2.0 so I decided to keep that part.

2016-09-27 12:00 UTC, nenko-tabakov commented on src/main/java/org/ehcache/integrations/shiro/EhCacheManager.java
> +            manager = CacheManagerBuilder.newCacheManager(createConfiguration());
This is how it is in the current CacheManager using EhCache 2.0. You are right I'll move the initialization to the constructor.

2016-09-27 13:27 UTC, chrisdennis commented on src/main/java/org/ehcache/integrations/shiro/EhCache.java
> +        cache.put(k, v);
Damn, it is yes.  Regardless I assume this is intended to be atomic... so we'll have to achieve this somehow.  Simplest solution would seem to be a loop involving `putIfAbsent(K, V)` and `replace(K, V)`.

2016-09-27 13:28 UTC, nenko-tabakov commented on src/main/java/org/ehcache/integrations/shiro/EhCache.java
> +        cache.put(k, v);
It's not atomic in the current implementation. Actually it is exactly like coded here :)

2016-09-27 13:29 UTC, chrisdennis commented on src/main/java/org/ehcache/integrations/shiro/EhCache.java
> +        cache.remove(k);
Right here too.  This is more awkward however... I can't see how we can do this without  relying on the equals contract of the stored values which is not great.  Maybe we can do some ugly punching through to the impl methods used by the JSR-107 layer?  @ljacomet any thoughts?

2016-09-27 13:29 UTC, chrisdennis commented on src/main/java/org/ehcache/integrations/shiro/EhCacheManager.java
> +            CacheConfigurationBuilder<Object, Object> configurationBuilder = xmlConfiguration.newCacheConfigurationBuilderFromTemplate(
Okay then, lets leave it as is.

2016-09-27 13:30 UTC, chrisdennis commented on src/main/java/org/ehcache/integrations/shiro/EhCache.java
> +        cache.put(k, v);
Hmm... any chance you could dig in to their code to find out how they use this.  If it's not atomic then unless they have their own exclusion mechanism I can't see how this return value could be useful.

2016-09-28 08:47 UTC, ljacomet approved these changes

2016-09-28 08:48 UTC, ljacomet commented
Going to merge this an open issues for work that ames up through reviews or by going over Shiro's usage of the API.

2016-09-28 08:51 UTC, merged